-- Migration 000004: Work Orders, Work Order Events (append-only audit), Cost Items

CREATE TABLE IF NOT EXISTS work_orders (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL,
    property_id BIGINT UNSIGNED NOT NULL,
    unit_id BIGINT UNSIGNED DEFAULT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    assigned_to BIGINT UNSIGNED DEFAULT NULL,
    title VARCHAR(255) NOT NULL DEFAULT '',
    description TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'Normal',
    status VARCHAR(30) NOT NULL DEFAULT 'New',
    issue_type VARCHAR(100) DEFAULT NULL,
    skill_tag VARCHAR(100) DEFAULT NULL,
    tags JSON DEFAULT NULL,
    preferred_access_date DATE DEFAULT NULL,
    preferred_access_start_time VARCHAR(20) DEFAULT NULL,
    preferred_access_end_time VARCHAR(20) DEFAULT NULL,
    sla_due_at TIMESTAMP NULL DEFAULT NULL,
    sla_breached_at TIMESTAMP NULL DEFAULT NULL,
    rating TINYINT UNSIGNED DEFAULT NULL,
    feedback TEXT DEFAULT NULL,
    completed_at TIMESTAMP NULL DEFAULT NULL,
    archived_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    UNIQUE INDEX idx_work_orders_uuid (uuid),
    INDEX idx_work_orders_property_status_created (property_id, status, created_at),
    INDEX idx_work_orders_tenant (tenant_id),
    INDEX idx_work_orders_assigned (assigned_to),
    INDEX idx_work_orders_sla_due (sla_due_at),
    INDEX idx_work_orders_status (status),
    INDEX idx_work_orders_deleted_at (deleted_at),
    CONSTRAINT fk_work_orders_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE RESTRICT,
    CONSTRAINT fk_work_orders_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL,
    CONSTRAINT fk_work_orders_tenant FOREIGN KEY (tenant_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_work_orders_assigned FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS work_order_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    work_order_id BIGINT UNSIGNED NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    actor_id BIGINT UNSIGNED DEFAULT NULL,
    from_status VARCHAR(30) DEFAULT NULL,
    to_status VARCHAR(30) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    metadata JSON DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_wo_events_work_order (work_order_id),
    INDEX idx_wo_events_type (event_type),
    INDEX idx_wo_events_created (created_at),
    CONSTRAINT fk_wo_events_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_wo_events_actor FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cost_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL,
    work_order_id BIGINT UNSIGNED NOT NULL,
    cost_type VARCHAR(20) NOT NULL,
    description VARCHAR(500) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    responsibility VARCHAR(20) NOT NULL DEFAULT 'Property',
    notes TEXT DEFAULT NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX idx_cost_items_uuid (uuid),
    INDEX idx_cost_items_work_order (work_order_id),
    CONSTRAINT fk_cost_items_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_cost_items_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
